In [40]:
# Import required libraries
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

Load the dataset using Pandas

In [41]:
df = pd.read_csv("/content/diabetes.csv")
df.head(5)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

Explore the dataset

In [42]:
print("Shape of Dataset:")
print(df.shape)

Shape of Dataset:
(768, 9)

In [43]:
print("Column Names:")
print(df.columns)

Column Names:
Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [44]:
print("Data Types:")
print(df.dtypes)

Data Types:
Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [45]:
print("Missing Values:")
print(df.isnull().sum())

Missing Values:
Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [9]:
print("Dataset Summary:")
df.describe()

Dataset Summary:

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

Separate the dataset into features and target variables

In [46]:
# Features
X = df.drop("Outcome", axis=1)

# Target
y = df["Outcome"]

print("Features Shape:", X.shape)
print("Target Shape:", y.shape)

Features Shape: (768, 8)
Target Shape: (768,)

In [47]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training Features:", X_train.shape)
print("Testing Features:", X_test.shape)
print("Training Labels:", y_train.shape)
print("Testing Labels:", y_test.shape)

Training Features: (614, 8)
Testing Features: (154, 8)
Training Labels: (614,)
Testing Labels: (154,)

Apply feature scaling using StandardScaler

In [48]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

In [49]:
print("Scaled Training Data (First 5 Rows):")
print(X_train_scaled[:5])

print("\nScaled Testing Data (First 5 Rows):")
print(X_test_scaled[:5])

Scaled Training Data (First 5 Rows):
[[-0.52639686 -1.15139792 -3.75268255 -1.32277365 -0.70120553 -4.13525578
  -0.49073479 -1.03594038]
 [ 1.58804586 -0.27664283  0.68034485  0.23350519 -0.70120553 -0.48916881
   2.41502991  1.48710085]
 [-0.82846011  0.56687102 -1.2658623  -0.09071957  0.01344832 -0.42452187
   0.54916055 -0.94893896]
 [-1.13052335  1.2541786  -1.04961706 -1.32277365 -0.70120553 -1.30372015
  -0.63929127  2.79212217]
 [ 0.68185612  0.41066475  0.57222224  1.07648956  2.48460077  1.83812075
  -0.68682934  1.13909516]]

Scaled Testing Data (First 5 Rows):
[[ 0.68185612 -0.71402038 -0.61712658  0.81710976  0.93474906  0.26073561
  -0.11637247  0.87809089]
 [-0.52639686 -0.27664283  0.30191569  0.7522648  -0.70120553  0.48053518
  -0.954231   -1.03594038]
 [-0.52639686 -0.40160784 -0.29275872 -1.32277365 -0.70120553 -0.15300476
  -0.9245197  -1.03594038]
 [ 1.28598261 -0.43284909  0.57222224 -1.32277365 -0.70120553 -0.95462672
   1.14932872  0.0950781 ]
 [ 0.98391937  0.47314726  1.11283533 -1.32277365 -0.70120553 -0.26936924
  -0.77002097  1.48710085]]

**PART 2**v - Building Artificial Nueral Network

In [50]:
import tensorflow as tf
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras import layers
from tensorflow.keras.layers import Dense, Conv2D, MaxPooling2D, Flatten, InputLayer

In [51]:
# Create Sequential Model for tabular data
model = Sequential([
    layers.Input(shape=(X_train_scaled.shape[1],), name="input_layer"), # Input layer matching tabular data features
    layers.Dense(units=32, activation='relu', name="hiddenlayer_1"), # Increased units to 32
    layers.Dense(units=16, activation='relu', name="hiddenlayer_2"), # Increased units to 16
    layers.Dense(units=1, activation='sigmoid', name="output_layer") # Output layer for binary classification
])

In [52]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [53]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ hiddenlayer_1 (Dense)           │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ hiddenlayer_2 (Dense)           │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ output_layer (Dense)            │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 833 (3.25 KB)

 Trainable params: 833 (3.25 KB)

 Non-trainable params: 0 (0.00 B)

**Part 3 - Model Training**

In [54]:
# Train the ANN model

history = model.fit(
    X_train_scaled,
    y_train,
    epochs=250,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

Epoch 1/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 2s 36ms/step - accuracy: 0.6517 - loss: 0.6619 - val_accuracy: 0.6504 - val_loss: 0.6602
Epoch 2/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6904 - loss: 0.6092 - val_accuracy: 0.6667 - val_loss: 0.6175
Epoch 3/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7169 - loss: 0.5716 - val_accuracy: 0.6748 - val_loss: 0.5830
Epoch 4/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7617 - loss: 0.5379 - val_accuracy: 0.7236 - val_loss: 0.5530
Epoch 5/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7780 - loss: 0.5128 - val_accuracy: 0.7398 - val_loss: 0.5276
Epoch 6/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7780 - loss: 0.4936 - val_accuracy: 0.7317 - val_loss: 0.5106
Epoch 7/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7862 - loss: 0.4785 - val_accuracy: 0.7561 - val_loss: 0.4957
Epoch 8/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7862 - loss: 0.4679 - val_accuracy: 0.7724 - val_loss: 0.4864
Epoch 9/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7943 - loss: 0.4599 - val_accuracy: 0.7805 - val_loss: 0.4802
Epoch 10/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7902 - loss: 0.4530 - val_accuracy: 0.7724 - val_loss: 0.4771
Epoch 11/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7923 - loss: 0.4480 - val_accuracy: 0.7724 - val_loss: 0.4721
Epoch 12/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7882 - loss: 0.4433 - val_accuracy: 0.7724 - val_loss: 0.4716
Epoch 13/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7923 - loss: 0.4408 - val_accuracy: 0.7886 - val_loss: 0.4694
Epoch 14/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7943 - loss: 0.4369 - val_accuracy: 0.7805 - val_loss: 0.4696
Epoch 15/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7943 - loss: 0.4333 - val_accuracy: 0.7886 - val_loss: 0.4693
Epoch 16/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7963 - loss: 0.4308 - val_accuracy: 0.7886 - val_loss: 0.4697
Epoch 17/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7984 - loss: 0.4296 - val_accuracy: 0.7724 - val_loss: 0.4687
Epoch 18/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7923 - loss: 0.4262 - val_accuracy: 0.7805 - val_loss: 0.4720
Epoch 19/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7882 - loss: 0.4253 - val_accuracy: 0.7724 - val_loss: 0.4709
Epoch 20/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7943 - loss: 0.4223 - val_accuracy: 0.7561 - val_loss: 0.4729
Epoch 21/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8004 - loss: 0.4198 - val_accuracy: 0.7561 - val_loss: 0.4731
Epoch 22/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7923 - loss: 0.4189 - val_accuracy: 0.7642 - val_loss: 0.4717
Epoch 23/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8004 - loss: 0.4160 - val_accuracy: 0.7642 - val_loss: 0.4734
Epoch 24/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8024 - loss: 0.4157 - val_accuracy: 0.7561 - val_loss: 0.4748
Epoch 25/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7984 - loss: 0.4129 - val_accuracy: 0.7642 - val_loss: 0.4735
Epoch 26/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7963 - loss: 0.4111 - val_accuracy: 0.7561 - val_loss: 0.4731
Epoch 27/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7963 - loss: 0.4095 - val_accuracy: 0.7561 - val_loss: 0.4762
Epoch 28/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7943 - loss: 0.4090 - val_accuracy: 0.7642 - val_loss: 0.4755
Epoch 29/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8045 - loss: 0.4075 - val_accuracy: 0.7561 - val_loss: 0.4771
Epoch 30/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8004 - loss: 0.4054 - val_accuracy: 0.7642 - val_loss: 0.4758
Epoch 31/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8045 - loss: 0.4035 - val_accuracy: 0.7642 - val_loss: 0.4758
Epoch 32/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8004 - loss: 0.4033 - val_accuracy: 0.7642 - val_loss: 0.4752
Epoch 33/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8024 - loss: 0.4004 - val_accuracy: 0.7642 - val_loss: 0.4757
Epoch 34/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8045 - loss: 0.3989 - val_accuracy: 0.7642 - val_loss: 0.4747
Epoch 35/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8086 - loss: 0.3986 - val_accuracy: 0.7724 - val_loss: 0.4760
Epoch 36/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8065 - loss: 0.3964 - val_accuracy: 0.7724 - val_loss: 0.4753
Epoch 37/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8065 - loss: 0.3951 - val_accuracy: 0.7724 - val_loss: 0.4762
Epoch 38/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8065 - loss: 0.3946 - val_accuracy: 0.7642 - val_loss: 0.4767
Epoch 39/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8045 - loss: 0.3937 - val_accuracy: 0.7642 - val_loss: 0.4745
Epoch 40/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8045 - loss: 0.3921 - val_accuracy: 0.7724 - val_loss: 0.4761
Epoch 41/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8045 - loss: 0.3909 - val_accuracy: 0.7724 - val_loss: 0.4772
Epoch 42/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8106 - loss: 0.3912 - val_accuracy: 0.7724 - val_loss: 0.4759
Epoch 43/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8126 - loss: 0.3881 - val_accuracy: 0.7642 - val_loss: 0.4769
Epoch 44/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8126 - loss: 0.3878 - val_accuracy: 0.7642 - val_loss: 0.4759
Epoch 45/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8208 - loss: 0.3852 - val_accuracy: 0.7724 - val_loss: 0.4766
Epoch 46/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8126 - loss: 0.3860 - val_accuracy: 0.7724 - val_loss: 0.4775
Epoch 47/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8228 - loss: 0.3830 - val_accuracy: 0.7724 - val_loss: 0.4766
Epoch 48/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8248 - loss: 0.3826 - val_accuracy: 0.7642 - val_loss: 0.4789
Epoch 49/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8208 - loss: 0.3808 - val_accuracy: 0.7642 - val_loss: 0.4780
Epoch 50/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8187 - loss: 0.3813 - val_accuracy: 0.7805 - val_loss: 0.4798
Epoch 51/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8228 - loss: 0.3798 - val_accuracy: 0.7724 - val_loss: 0.4785
Epoch 52/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8269 - loss: 0.3781 - val_accuracy: 0.7724 - val_loss: 0.4783
Epoch 53/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8289 - loss: 0.3771 - val_accuracy: 0.7805 - val_loss: 0.4794
Epoch 54/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8208 - loss: 0.3779 - val_accuracy: 0.7724 - val_loss: 0.4783
Epoch 55/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8330 - loss: 0.3745 - val_accuracy: 0.7805 - val_loss: 0.4810
Epoch 56/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8269 - loss: 0.3742 - val_accuracy: 0.7805 - val_loss: 0.4806
Epoch 57/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8350 - loss: 0.3725 - val_accuracy: 0.7724 - val_loss: 0.4777
Epoch 58/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8411 - loss: 0.3724 - val_accuracy: 0.7805 - val_loss: 0.4798
Epoch 59/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8350 - loss: 0.3709 - val_accuracy: 0.7805 - val_loss: 0.4812
Epoch 60/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8411 - loss: 0.3702 - val_accuracy: 0.7805 - val_loss: 0.4815
Epoch 61/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8371 - loss: 0.3684 - val_accuracy: 0.7724 - val_loss: 0.4807
Epoch 62/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8371 - loss: 0.3673 - val_accuracy: 0.7805 - val_loss: 0.4809
Epoch 63/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8371 - loss: 0.3690 - val_accuracy: 0.7724 - val_loss: 0.4797
Epoch 64/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8391 - loss: 0.3660 - val_accuracy: 0.7805 - val_loss: 0.4828
Epoch 65/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8371 - loss: 0.3645 - val_accuracy: 0.7724 - val_loss: 0.4816
Epoch 66/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8330 - loss: 0.3627 - val_accuracy: 0.7805 - val_loss: 0.4829
Epoch 67/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8391 - loss: 0.3640 - val_accuracy: 0.7805 - val_loss: 0.4845
Epoch 68/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8411 - loss: 0.3619 - val_accuracy: 0.7724 - val_loss: 0.4824
Epoch 69/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8452 - loss: 0.3613 - val_accuracy: 0.7805 - val_loss: 0.4856
Epoch 70/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8391 - loss: 0.3607 - val_accuracy: 0.7805 - val_loss: 0.4851
Epoch 71/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8432 - loss: 0.3575 - val_accuracy: 0.7805 - val_loss: 0.4820
Epoch 72/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8411 - loss: 0.3600 - val_accuracy: 0.7805 - val_loss: 0.4820
Epoch 73/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8411 - loss: 0.3575 - val_accuracy: 0.7886 - val_loss: 0.4847
Epoch 74/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8432 - loss: 0.3550 - val_accuracy: 0.7886 - val_loss: 0.4847
Epoch 75/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8452 - loss: 0.3547 - val_accuracy: 0.7886 - val_loss: 0.4850
Epoch 76/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8452 - loss: 0.3542 - val_accuracy: 0.7886 - val_loss: 0.4842
Epoch 77/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8493 - loss: 0.3525 - val_accuracy: 0.7886 - val_loss: 0.4854
Epoch 78/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8473 - loss: 0.3518 - val_accuracy: 0.7886 - val_loss: 0.4875
Epoch 79/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8452 - loss: 0.3516 - val_accuracy: 0.7886 - val_loss: 0.4853
Epoch 80/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8513 - loss: 0.3494 - val_accuracy: 0.7886 - val_loss: 0.4848
Epoch 81/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8473 - loss: 0.3493 - val_accuracy: 0.7886 - val_loss: 0.4854
Epoch 82/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8534 - loss: 0.3481 - val_accuracy: 0.7805 - val_loss: 0.4887
Epoch 83/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8574 - loss: 0.3465 - val_accuracy: 0.7724 - val_loss: 0.4863
Epoch 84/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8595 - loss: 0.3457 - val_accuracy: 0.7886 - val_loss: 0.4887
Epoch 85/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8615 - loss: 0.3448 - val_accuracy: 0.7886 - val_loss: 0.4871
Epoch 86/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8534 - loss: 0.3449 - val_accuracy: 0.7886 - val_loss: 0.4864
Epoch 87/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8595 - loss: 0.3435 - val_accuracy: 0.7805 - val_loss: 0.4923
Epoch 88/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8656 - loss: 0.3418 - val_accuracy: 0.7805 - val_loss: 0.4868
Epoch 89/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8595 - loss: 0.3417 - val_accuracy: 0.7886 - val_loss: 0.4868
Epoch 90/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8595 - loss: 0.3420 - val_accuracy: 0.7886 - val_loss: 0.4898
Epoch 91/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8615 - loss: 0.3377 - val_accuracy: 0.7805 - val_loss: 0.4881
Epoch 92/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8676 - loss: 0.3393 - val_accuracy: 0.7805 - val_loss: 0.4900
Epoch 93/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8615 - loss: 0.3373 - val_accuracy: 0.7805 - val_loss: 0.4920
Epoch 94/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8574 - loss: 0.3374 - val_accuracy: 0.7805 - val_loss: 0.4873
Epoch 95/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8635 - loss: 0.3357 - val_accuracy: 0.7805 - val_loss: 0.4882
Epoch 96/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8615 - loss: 0.3358 - val_accuracy: 0.7805 - val_loss: 0.4898
Epoch 97/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8656 - loss: 0.3349 - val_accuracy: 0.7805 - val_loss: 0.4871
Epoch 98/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8717 - loss: 0.3340 - val_accuracy: 0.7805 - val_loss: 0.4918
Epoch 99/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8676 - loss: 0.3304 - val_accuracy: 0.7805 - val_loss: 0.4916
Epoch 100/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8574 - loss: 0.3320 - val_accuracy: 0.7886 - val_loss: 0.4920
Epoch 101/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8656 - loss: 0.3301 - val_accuracy: 0.7805 - val_loss: 0.4883
Epoch 102/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8676 - loss: 0.3288 - val_accuracy: 0.7805 - val_loss: 0.4882
Epoch 103/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8697 - loss: 0.3295 - val_accuracy: 0.7805 - val_loss: 0.4897
Epoch 104/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8717 - loss: 0.3266 - val_accuracy: 0.7805 - val_loss: 0.4924
Epoch 105/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8717 - loss: 0.3254 - val_accuracy: 0.7805 - val_loss: 0.4911
Epoch 106/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8676 - loss: 0.3254 - val_accuracy: 0.7805 - val_loss: 0.4927
Epoch 107/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8697 - loss: 0.3242 - val_accuracy: 0.7805 - val_loss: 0.4912
Epoch 108/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8717 - loss: 0.3231 - val_accuracy: 0.7805 - val_loss: 0.4952
Epoch 109/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8697 - loss: 0.3210 - val_accuracy: 0.7805 - val_loss: 0.4918
Epoch 110/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8717 - loss: 0.3202 - val_accuracy: 0.7805 - val_loss: 0.4936
Epoch 111/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8697 - loss: 0.3197 - val_accuracy: 0.7805 - val_loss: 0.4987
Epoch 112/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8615 - loss: 0.3190 - val_accuracy: 0.7724 - val_loss: 0.5016
Epoch 113/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8697 - loss: 0.3177 - val_accuracy: 0.7724 - val_loss: 0.4964
Epoch 114/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8717 - loss: 0.3173 - val_accuracy: 0.7724 - val_loss: 0.5009
Epoch 115/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8697 - loss: 0.3155 - val_accuracy: 0.7724 - val_loss: 0.4972
Epoch 116/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8717 - loss: 0.3152 - val_accuracy: 0.7724 - val_loss: 0.4998
Epoch 117/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8737 - loss: 0.3127 - val_accuracy: 0.7724 - val_loss: 0.5030
Epoch 118/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8798 - loss: 0.3124 - val_accuracy: 0.7724 - val_loss: 0.5025
Epoch 119/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8778 - loss: 0.3113 - val_accuracy: 0.7724 - val_loss: 0.5047
Epoch 120/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8798 - loss: 0.3118 - val_accuracy: 0.7724 - val_loss: 0.5106
Epoch 121/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8798 - loss: 0.3087 - val_accuracy: 0.7724 - val_loss: 0.5111
Epoch 122/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8737 - loss: 0.3101 - val_accuracy: 0.7724 - val_loss: 0.5076
Epoch 123/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8798 - loss: 0.3068 - val_accuracy: 0.7724 - val_loss: 0.5060
Epoch 124/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8798 - loss: 0.3072 - val_accuracy: 0.7724 - val_loss: 0.5062
Epoch 125/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8778 - loss: 0.3050 - val_accuracy: 0.7724 - val_loss: 0.5089
Epoch 126/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8778 - loss: 0.3043 - val_accuracy: 0.7724 - val_loss: 0.5115
Epoch 127/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8798 - loss: 0.3025 - val_accuracy: 0.7724 - val_loss: 0.5116
Epoch 128/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8859 - loss: 0.3015 - val_accuracy: 0.7724 - val_loss: 0.5170
Epoch 129/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8778 - loss: 0.3020 - val_accuracy: 0.7724 - val_loss: 0.5175
Epoch 130/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8819 - loss: 0.3008 - val_accuracy: 0.7724 - val_loss: 0.5112
Epoch 131/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8798 - loss: 0.3013 - val_accuracy: 0.7805 - val_loss: 0.5211
Epoch 132/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8839 - loss: 0.2984 - val_accuracy: 0.7724 - val_loss: 0.5147
Epoch 133/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8819 - loss: 0.2982 - val_accuracy: 0.7724 - val_loss: 0.5179
Epoch 134/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8839 - loss: 0.2973 - val_accuracy: 0.7724 - val_loss: 0.5178
Epoch 135/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8859 - loss: 0.2961 - val_accuracy: 0.7724 - val_loss: 0.5180
Epoch 136/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8819 - loss: 0.2949 - val_accuracy: 0.7724 - val_loss: 0.5171
Epoch 137/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8839 - loss: 0.2933 - val_accuracy: 0.7724 - val_loss: 0.5163
Epoch 138/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8880 - loss: 0.2924 - val_accuracy: 0.7724 - val_loss: 0.5170
Epoch 139/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8839 - loss: 0.2918 - val_accuracy: 0.7724 - val_loss: 0.5181
Epoch 140/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8819 - loss: 0.2907 - val_accuracy: 0.7724 - val_loss: 0.5188
Epoch 141/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8900 - loss: 0.2916 - val_accuracy: 0.7724 - val_loss: 0.5247
Epoch 142/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8941 - loss: 0.2894 - val_accuracy: 0.7724 - val_loss: 0.5218
Epoch 143/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8839 - loss: 0.2882 - val_accuracy: 0.7724 - val_loss: 0.5254
Epoch 144/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8921 - loss: 0.2863 - val_accuracy: 0.7724 - val_loss: 0.5269
Epoch 145/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8921 - loss: 0.2858 - val_accuracy: 0.7724 - val_loss: 0.5277
Epoch 146/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8921 - loss: 0.2864 - val_accuracy: 0.7724 - val_loss: 0.5242
Epoch 147/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8880 - loss: 0.2843 - val_accuracy: 0.7724 - val_loss: 0.5208
Epoch 148/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8900 - loss: 0.2840 - val_accuracy: 0.7724 - val_loss: 0.5275
Epoch 149/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8941 - loss: 0.2813 - val_accuracy: 0.7724 - val_loss: 0.5279
Epoch 150/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8880 - loss: 0.2810 - val_accuracy: 0.7642 - val_loss: 0.5298
Epoch 151/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8880 - loss: 0.2807 - val_accuracy: 0.7724 - val_loss: 0.5320
Epoch 152/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8921 - loss: 0.2796 - val_accuracy: 0.7724 - val_loss: 0.5355
Epoch 153/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8941 - loss: 0.2769 - val_accuracy: 0.7724 - val_loss: 0.5333
Epoch 154/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8921 - loss: 0.2771 - val_accuracy: 0.7724 - val_loss: 0.5333
Epoch 155/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8900 - loss: 0.2766 - val_accuracy: 0.7724 - val_loss: 0.5334
Epoch 156/250

In [55]:
# Display Final Training Accuracy

final_accuracy = history.history['accuracy'][-1]

print("Final Training Accuracy:", round(final_accuracy * 100, 2), "%")

Final Training Accuracy: 93.69 %

In [56]:
print("Number of Epochs Used:", len(history.history['accuracy']))

Number of Epochs Used: 250

**Part 4 - Model Evaluation**

In [57]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [58]:
# Predict probabilities on the test dataset
y_pred_prob = model.predict(X_test_scaled)

# Display first 5 predicted probabilities
print(y_pred_prob[:5])

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step
[[0.7116625 ]
 [0.01378968]
 [0.0056629 ]
 [0.08426597]
 [0.19869672]]

In [59]:
# Convert probabilities to binary predictions
y_pred = (y_pred_prob >= 0.5).astype(int)

In [60]:
accuracy = accuracy_score(y_test, y_pred)

print("Model Accuracy:", round(accuracy * 100, 2), "%")

Model Accuracy: 68.18 %

In [61]:
cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[74 25]
 [24 31]]

In [62]:
import pandas as pd

cm_df = pd.DataFrame(
    cm,
    index=["Actual: No Diabetes", "Actual: Diabetes"],
    columns=["Predicted: No Diabetes", "Predicted: Diabetes"]
)

cm_df

                     Predicted: No Diabetes  Predicted: Diabetes
Actual: No Diabetes                      74                   25
Actual: Diabetes                         24                   31

## Confusion Matrix Summary
The ANN model showed the following performance in predicting diabetes:

*   Out of **99** patients who truly did not have diabetes (Actual: No Diabetes), the model correctly identified **74** as 'No Diabetes' (True Negatives).
*   The model incorrectly predicted that **25** of these patients had diabetes (False Positives).
*   Out of **55** patients who truly had diabetes (Actual: Diabetes), the model correctly identified **31** as 'Diabetes' (True Positives).
*   The model incorrectly predicted that **24** of these patients did not have diabetes (False Negatives).