In [1]:
# Import required libraries
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

Load the dataset using Pandas

In [2]:
df = pd.read_csv("/content/diabetes.csv")
df.head(5)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

Explore the dataset

In [3]:
print("Shape of Dataset:")
print(df.shape)

Shape of Dataset:
(768, 9)

In [4]:
print("Column Names:")
print(df.columns)

Column Names:
Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome'],
      dtype='object')

In [5]:
print("Data Types:")
print(df.dtypes)

Data Types:
Pregnancies                   int64
Glucose                       int64
BloodPressure                 int64
SkinThickness                 int64
Insulin                       int64
BMI                         float64
DiabetesPedigreeFunction    float64
Age                           int64
Outcome                       int64
dtype: object

In [6]:
print("Missing Values:")
print(df.isnull().sum())

Missing Values:
Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [7]:
print("Dataset Summary:")
df.describe()

Dataset Summary:

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

Separate the dataset into features and target variables

In [8]:
# Features
X = df.drop("Outcome", axis=1)

# Target
y = df["Outcome"]

print("Features Shape:", X.shape)
print("Target Shape:", y.shape)

Features Shape: (768, 8)
Target Shape: (768,)

In [9]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training Features:", X_train.shape)
print("Testing Features:", X_test.shape)
print("Training Labels:", y_train.shape)
print("Testing Labels:", y_test.shape)

Training Features: (614, 8)
Testing Features: (154, 8)
Training Labels: (614,)
Testing Labels: (154,)

Apply feature scaling using StandardScaler

In [11]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)

X_test_scaled = scaler.transform(X_test)

In [12]:
print("Scaled Training Data (First 5 Rows):")
print(X_train_scaled[:5])

print("\nScaled Testing Data (First 5 Rows):")
print(X_test_scaled[:5])

Scaled Training Data (First 5 Rows):
[[-0.52639686 -1.15139792 -3.75268255 -1.32277365 -0.70120553 -4.13525578
  -0.49073479 -1.03594038]
 [ 1.58804586 -0.27664283  0.68034485  0.23350519 -0.70120553 -0.48916881
   2.41502991  1.48710085]
 [-0.82846011  0.56687102 -1.2658623  -0.09071957  0.01344832 -0.42452187
   0.54916055 -0.94893896]
 [-1.13052335  1.2541786  -1.04961706 -1.32277365 -0.70120553 -1.30372015
  -0.63929127  2.79212217]
 [ 0.68185612  0.41066475  0.57222224  1.07648956  2.48460077  1.83812075
  -0.68682934  1.13909516]]

Scaled Testing Data (First 5 Rows):
[[ 0.68185612 -0.71402038 -0.61712658  0.81710976  0.93474906  0.26073561
  -0.11637247  0.87809089]
 [-0.52639686 -0.27664283  0.30191569  0.7522648  -0.70120553  0.48053518
  -0.954231   -1.03594038]
 [-0.52639686 -0.40160784 -0.29275872 -1.32277365 -0.70120553 -0.15300476
  -0.9245197  -1.03594038]
 [ 1.28598261 -0.43284909  0.57222224 -1.32277365 -0.70120553 -0.95462672
   1.14932872  0.0950781 ]
 [ 0.98391937  0.47314726  1.11283533 -1.32277365 -0.70120553 -0.26936924
  -0.77002097  1.48710085]]

**PART 2**v - Building Artificial Nueral Network

In [13]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [14]:
# Create Sequential Model
model = Sequential()

In [15]:
# Input Layer + First Hidden Layer
model.add(Dense(units=16, activation='relu', input_shape=(X_train_scaled.shape[1],)))

# Second Hidden Layer
model.add(Dense(units=8, activation='relu'))

# Output Layer
model.add(Dense(units=1, activation='sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [16]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

In [17]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 16)             │           144 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 289 (1.13 KB)

 Trainable params: 289 (1.13 KB)

 Non-trainable params: 0 (0.00 B)

**Part 3 - Model Training**

In [22]:
# Train the ANN model

history = model.fit(
    X_train_scaled,
    y_train,
    epochs=250,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)

Epoch 1/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8350 - loss: 0.3552 - val_accuracy: 0.7480 - val_loss: 0.5106
Epoch 2/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8350 - loss: 0.3556 - val_accuracy: 0.7480 - val_loss: 0.5099
Epoch 3/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8493 - loss: 0.3549 - val_accuracy: 0.7480 - val_loss: 0.5111
Epoch 4/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8391 - loss: 0.3548 - val_accuracy: 0.7480 - val_loss: 0.5117
Epoch 5/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8371 - loss: 0.3537 - val_accuracy: 0.7480 - val_loss: 0.5128
Epoch 6/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8493 - loss: 0.3539 - val_accuracy: 0.7480 - val_loss: 0.5118
Epoch 7/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8493 - loss: 0.3537 - val_accuracy: 0.7480 - val_loss: 0.5150
Epoch 8/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8452 - loss: 0.3528 - val_accuracy: 0.7480 - val_loss: 0.5163
Epoch 9/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8432 - loss: 0.3526 - val_accuracy: 0.7480 - val_loss: 0.5158
Epoch 10/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8452 - loss: 0.3526 - val_accuracy: 0.7480 - val_loss: 0.5167
Epoch 11/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8432 - loss: 0.3518 - val_accuracy: 0.7480 - val_loss: 0.5166
Epoch 12/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8473 - loss: 0.3513 - val_accuracy: 0.7480 - val_loss: 0.5172
Epoch 13/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8493 - loss: 0.3512 - val_accuracy: 0.7480 - val_loss: 0.5165
Epoch 14/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8473 - loss: 0.3508 - val_accuracy: 0.7480 - val_loss: 0.5166
Epoch 15/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8493 - loss: 0.3513 - val_accuracy: 0.7480 - val_loss: 0.5182
Epoch 16/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8411 - loss: 0.3509 - val_accuracy: 0.7480 - val_loss: 0.5202
Epoch 17/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8473 - loss: 0.3503 - val_accuracy: 0.7480 - val_loss: 0.5170
Epoch 18/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8513 - loss: 0.3495 - val_accuracy: 0.7480 - val_loss: 0.5172
Epoch 19/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8493 - loss: 0.3491 - val_accuracy: 0.7480 - val_loss: 0.5182
Epoch 20/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8554 - loss: 0.3488 - val_accuracy: 0.7480 - val_loss: 0.5163
Epoch 21/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8534 - loss: 0.3485 - val_accuracy: 0.7480 - val_loss: 0.5194
Epoch 22/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8534 - loss: 0.3480 - val_accuracy: 0.7480 - val_loss: 0.5188
Epoch 23/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8493 - loss: 0.3485 - val_accuracy: 0.7398 - val_loss: 0.5206
Epoch 24/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8513 - loss: 0.3469 - val_accuracy: 0.7480 - val_loss: 0.5202
Epoch 25/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8513 - loss: 0.3471 - val_accuracy: 0.7480 - val_loss: 0.5209
Epoch 26/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8534 - loss: 0.3469 - val_accuracy: 0.7480 - val_loss: 0.5208
Epoch 27/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8513 - loss: 0.3468 - val_accuracy: 0.7480 - val_loss: 0.5213
Epoch 28/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8513 - loss: 0.3460 - val_accuracy: 0.7480 - val_loss: 0.5229
Epoch 29/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8534 - loss: 0.3458 - val_accuracy: 0.7480 - val_loss: 0.5221
Epoch 30/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8534 - loss: 0.3453 - val_accuracy: 0.7480 - val_loss: 0.5233
Epoch 31/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8534 - loss: 0.3452 - val_accuracy: 0.7480 - val_loss: 0.5259
Epoch 32/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8554 - loss: 0.3448 - val_accuracy: 0.7480 - val_loss: 0.5250
Epoch 33/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8534 - loss: 0.3445 - val_accuracy: 0.7398 - val_loss: 0.5239
Epoch 34/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8513 - loss: 0.3442 - val_accuracy: 0.7480 - val_loss: 0.5250
Epoch 35/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8534 - loss: 0.3436 - val_accuracy: 0.7480 - val_loss: 0.5233
Epoch 36/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8534 - loss: 0.3437 - val_accuracy: 0.7480 - val_loss: 0.5230
Epoch 37/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8513 - loss: 0.3433 - val_accuracy: 0.7480 - val_loss: 0.5264
Epoch 38/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8534 - loss: 0.3438 - val_accuracy: 0.7398 - val_loss: 0.5228
Epoch 39/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8534 - loss: 0.3424 - val_accuracy: 0.7398 - val_loss: 0.5247
Epoch 40/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8534 - loss: 0.3421 - val_accuracy: 0.7398 - val_loss: 0.5247
Epoch 41/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8513 - loss: 0.3422 - val_accuracy: 0.7398 - val_loss: 0.5239
Epoch 42/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8513 - loss: 0.3412 - val_accuracy: 0.7398 - val_loss: 0.5246
Epoch 43/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8534 - loss: 0.3415 - val_accuracy: 0.7398 - val_loss: 0.5242
Epoch 44/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8554 - loss: 0.3403 - val_accuracy: 0.7398 - val_loss: 0.5262
Epoch 45/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8534 - loss: 0.3405 - val_accuracy: 0.7317 - val_loss: 0.5254
Epoch 46/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8554 - loss: 0.3401 - val_accuracy: 0.7398 - val_loss: 0.5262
Epoch 47/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8554 - loss: 0.3398 - val_accuracy: 0.7480 - val_loss: 0.5254
Epoch 48/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8534 - loss: 0.3401 - val_accuracy: 0.7317 - val_loss: 0.5265
Epoch 49/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8554 - loss: 0.3391 - val_accuracy: 0.7398 - val_loss: 0.5255
Epoch 50/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8574 - loss: 0.3389 - val_accuracy: 0.7480 - val_loss: 0.5286
Epoch 51/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8534 - loss: 0.3389 - val_accuracy: 0.7398 - val_loss: 0.5299
Epoch 52/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8554 - loss: 0.3379 - val_accuracy: 0.7398 - val_loss: 0.5285
Epoch 53/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8554 - loss: 0.3383 - val_accuracy: 0.7398 - val_loss: 0.5285
Epoch 54/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8554 - loss: 0.3373 - val_accuracy: 0.7480 - val_loss: 0.5253
Epoch 55/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8574 - loss: 0.3376 - val_accuracy: 0.7480 - val_loss: 0.5259
Epoch 56/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8574 - loss: 0.3375 - val_accuracy: 0.7480 - val_loss: 0.5286
Epoch 57/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8554 - loss: 0.3370 - val_accuracy: 0.7480 - val_loss: 0.5262
Epoch 58/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8534 - loss: 0.3363 - val_accuracy: 0.7317 - val_loss: 0.5281
Epoch 59/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8554 - loss: 0.3356 - val_accuracy: 0.7317 - val_loss: 0.5293
Epoch 60/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8554 - loss: 0.3361 - val_accuracy: 0.7480 - val_loss: 0.5276
Epoch 61/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8534 - loss: 0.3355 - val_accuracy: 0.7317 - val_loss: 0.5291
Epoch 62/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8554 - loss: 0.3353 - val_accuracy: 0.7480 - val_loss: 0.5286
Epoch 63/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8595 - loss: 0.3347 - val_accuracy: 0.7398 - val_loss: 0.5281
Epoch 64/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8534 - loss: 0.3351 - val_accuracy: 0.7480 - val_loss: 0.5310
Epoch 65/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8534 - loss: 0.3346 - val_accuracy: 0.7317 - val_loss: 0.5307
Epoch 66/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8554 - loss: 0.3343 - val_accuracy: 0.7480 - val_loss: 0.5300
Epoch 67/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8534 - loss: 0.3346 - val_accuracy: 0.7480 - val_loss: 0.5298
Epoch 68/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8513 - loss: 0.3331 - val_accuracy: 0.7480 - val_loss: 0.5316
Epoch 69/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8554 - loss: 0.3329 - val_accuracy: 0.7480 - val_loss: 0.5317
Epoch 70/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8574 - loss: 0.3326 - val_accuracy: 0.7480 - val_loss: 0.5311
Epoch 71/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8534 - loss: 0.3328 - val_accuracy: 0.7398 - val_loss: 0.5326
Epoch 72/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8534 - loss: 0.3326 - val_accuracy: 0.7398 - val_loss: 0.5337
Epoch 73/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8554 - loss: 0.3317 - val_accuracy: 0.7398 - val_loss: 0.5341
Epoch 74/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8554 - loss: 0.3323 - val_accuracy: 0.7398 - val_loss: 0.5347
Epoch 75/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8595 - loss: 0.3318 - val_accuracy: 0.7480 - val_loss: 0.5334
Epoch 76/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8534 - loss: 0.3314 - val_accuracy: 0.7480 - val_loss: 0.5336
Epoch 77/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8513 - loss: 0.3313 - val_accuracy: 0.7398 - val_loss: 0.5358
Epoch 78/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8595 - loss: 0.3305 - val_accuracy: 0.7480 - val_loss: 0.5356
Epoch 79/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8534 - loss: 0.3306 - val_accuracy: 0.7480 - val_loss: 0.5344
Epoch 80/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8554 - loss: 0.3301 - val_accuracy: 0.7398 - val_loss: 0.5357
Epoch 81/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8493 - loss: 0.3316 - val_accuracy: 0.7317 - val_loss: 0.5385
Epoch 82/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8534 - loss: 0.3300 - val_accuracy: 0.7398 - val_loss: 0.5362
Epoch 83/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8554 - loss: 0.3292 - val_accuracy: 0.7398 - val_loss: 0.5393
Epoch 84/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8595 - loss: 0.3293 - val_accuracy: 0.7398 - val_loss: 0.5387
Epoch 85/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8574 - loss: 0.3288 - val_accuracy: 0.7398 - val_loss: 0.5375
Epoch 86/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8574 - loss: 0.3282 - val_accuracy: 0.7398 - val_loss: 0.5378
Epoch 87/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8595 - loss: 0.3280 - val_accuracy: 0.7398 - val_loss: 0.5372
Epoch 88/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8574 - loss: 0.3285 - val_accuracy: 0.7480 - val_loss: 0.5384
Epoch 89/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8574 - loss: 0.3281 - val_accuracy: 0.7480 - val_loss: 0.5406
Epoch 90/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8534 - loss: 0.3272 - val_accuracy: 0.7398 - val_loss: 0.5377
Epoch 91/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8554 - loss: 0.3275 - val_accuracy: 0.7398 - val_loss: 0.5397
Epoch 92/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8595 - loss: 0.3266 - val_accuracy: 0.7398 - val_loss: 0.5419
Epoch 93/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8554 - loss: 0.3264 - val_accuracy: 0.7398 - val_loss: 0.5419
Epoch 94/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8574 - loss: 0.3265 - val_accuracy: 0.7398 - val_loss: 0.5413
Epoch 95/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8595 - loss: 0.3255 - val_accuracy: 0.7398 - val_loss: 0.5408
Epoch 96/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8574 - loss: 0.3254 - val_accuracy: 0.7398 - val_loss: 0.5420
Epoch 97/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8574 - loss: 0.3260 - val_accuracy: 0.7398 - val_loss: 0.5425
Epoch 98/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8534 - loss: 0.3266 - val_accuracy: 0.7480 - val_loss: 0.5398
Epoch 99/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8534 - loss: 0.3248 - val_accuracy: 0.7480 - val_loss: 0.5423
Epoch 100/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8595 - loss: 0.3247 - val_accuracy: 0.7317 - val_loss: 0.5434
Epoch 101/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8615 - loss: 0.3246 - val_accuracy: 0.7398 - val_loss: 0.5442
Epoch 102/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8615 - loss: 0.3236 - val_accuracy: 0.7398 - val_loss: 0.5444
Epoch 103/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8635 - loss: 0.3237 - val_accuracy: 0.7398 - val_loss: 0.5452
Epoch 104/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8615 - loss: 0.3234 - val_accuracy: 0.7398 - val_loss: 0.5455
Epoch 105/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8574 - loss: 0.3233 - val_accuracy: 0.7317 - val_loss: 0.5439
Epoch 106/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8595 - loss: 0.3229 - val_accuracy: 0.7398 - val_loss: 0.5453
Epoch 107/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8595 - loss: 0.3224 - val_accuracy: 0.7398 - val_loss: 0.5445
Epoch 108/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8574 - loss: 0.3228 - val_accuracy: 0.7317 - val_loss: 0.5462
Epoch 109/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8554 - loss: 0.3227 - val_accuracy: 0.7398 - val_loss: 0.5477
Epoch 110/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8635 - loss: 0.3219 - val_accuracy: 0.7317 - val_loss: 0.5479
Epoch 111/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8595 - loss: 0.3218 - val_accuracy: 0.7236 - val_loss: 0.5477
Epoch 112/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8595 - loss: 0.3210 - val_accuracy: 0.7398 - val_loss: 0.5470
Epoch 113/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8615 - loss: 0.3211 - val_accuracy: 0.7398 - val_loss: 0.5492
Epoch 114/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8635 - loss: 0.3213 - val_accuracy: 0.7317 - val_loss: 0.5499
Epoch 115/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8595 - loss: 0.3203 - val_accuracy: 0.7398 - val_loss: 0.5502
Epoch 116/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8595 - loss: 0.3201 - val_accuracy: 0.7398 - val_loss: 0.5502
Epoch 117/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8615 - loss: 0.3191 - val_accuracy: 0.7317 - val_loss: 0.5511
Epoch 118/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8534 - loss: 0.3196 - val_accuracy: 0.7154 - val_loss: 0.5537
Epoch 119/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8513 - loss: 0.3195 - val_accuracy: 0.7561 - val_loss: 0.5519
Epoch 120/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8574 - loss: 0.3188 - val_accuracy: 0.7236 - val_loss: 0.5524
Epoch 121/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8574 - loss: 0.3193 - val_accuracy: 0.7317 - val_loss: 0.5523
Epoch 122/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8635 - loss: 0.3193 - val_accuracy: 0.7561 - val_loss: 0.5521
Epoch 123/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8595 - loss: 0.3185 - val_accuracy: 0.7236 - val_loss: 0.5532
Epoch 124/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8574 - loss: 0.3195 - val_accuracy: 0.7398 - val_loss: 0.5519
Epoch 125/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8574 - loss: 0.3180 - val_accuracy: 0.7398 - val_loss: 0.5514
Epoch 126/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8554 - loss: 0.3177 - val_accuracy: 0.7236 - val_loss: 0.5535
Epoch 127/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8554 - loss: 0.3175 - val_accuracy: 0.7561 - val_loss: 0.5521
Epoch 128/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8574 - loss: 0.3164 - val_accuracy: 0.7236 - val_loss: 0.5535
Epoch 129/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8574 - loss: 0.3165 - val_accuracy: 0.7480 - val_loss: 0.5536
Epoch 130/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8635 - loss: 0.3160 - val_accuracy: 0.7480 - val_loss: 0.5548
Epoch 131/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8656 - loss: 0.3166 - val_accuracy: 0.7480 - val_loss: 0.5569
Epoch 132/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8554 - loss: 0.3154 - val_accuracy: 0.7236 - val_loss: 0.5553
Epoch 133/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8574 - loss: 0.3157 - val_accuracy: 0.7317 - val_loss: 0.5558
Epoch 134/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8615 - loss: 0.3154 - val_accuracy: 0.7480 - val_loss: 0.5575
Epoch 135/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8656 - loss: 0.3150 - val_accuracy: 0.7480 - val_loss: 0.5567
Epoch 136/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8676 - loss: 0.3151 - val_accuracy: 0.7480 - val_loss: 0.5567
Epoch 137/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8656 - loss: 0.3146 - val_accuracy: 0.7398 - val_loss: 0.5589
Epoch 138/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8656 - loss: 0.3138 - val_accuracy: 0.7398 - val_loss: 0.5587
Epoch 139/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8635 - loss: 0.3146 - val_accuracy: 0.7398 - val_loss: 0.5586
Epoch 140/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8615 - loss: 0.3138 - val_accuracy: 0.7317 - val_loss: 0.5599
Epoch 141/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8615 - loss: 0.3132 - val_accuracy: 0.7398 - val_loss: 0.5598
Epoch 142/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8635 - loss: 0.3136 - val_accuracy: 0.7317 - val_loss: 0.5609
Epoch 143/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8737 - loss: 0.3130 - val_accuracy: 0.7317 - val_loss: 0.5585
Epoch 144/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8697 - loss: 0.3127 - val_accuracy: 0.7317 - val_loss: 0.5604
Epoch 145/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8635 - loss: 0.3125 - val_accuracy: 0.7317 - val_loss: 0.5633
Epoch 146/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8656 - loss: 0.3129 - val_accuracy: 0.7317 - val_loss: 0.5626
Epoch 147/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8656 - loss: 0.3118 - val_accuracy: 0.7236 - val_loss: 0.5629
Epoch 148/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8656 - loss: 0.3116 - val_accuracy: 0.7317 - val_loss: 0.5636
Epoch 149/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8635 - loss: 0.3117 - val_accuracy: 0.7317 - val_loss: 0.5662
Epoch 150/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8635 - loss: 0.3114 - val_accuracy: 0.7236 - val_loss: 0.5643
Epoch 151/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8697 - loss: 0.3110 - val_accuracy: 0.7317 - val_loss: 0.5628
Epoch 152/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8656 - loss: 0.3110 - val_accuracy: 0.7317 - val_loss: 0.5645
Epoch 153/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8656 - loss: 0.3110 - val_accuracy: 0.7317 - val_loss: 0.5665
Epoch 154/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8676 - loss: 0.3110 - val_accuracy: 0.7398 - val_loss: 0.5641
Epoch 155/250
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8635 - loss: 0.3101 - val_accuracy: 0.7236 - val_loss: 0.5651
Epoch 156/250

In [30]:
# Display Final Training Accuracy

final_accuracy = history.history['accuracy'][-1]

print("Final Training Accuracy:", round(final_accuracy * 100, 2), "%")

Final Training Accuracy: 88.19 %

In [31]:
print("Number of Epochs Used:", len(history.history['accuracy']))

Number of Epochs Used: 250

**Part 4 - Model Evaluation**

In [32]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [33]:
# Predict probabilities on the test dataset
y_pred_prob = model.predict(X_test_scaled)

# Display first 5 predicted probabilities
print(y_pred_prob[:5])

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
[[0.4137412 ]
 [0.02073704]
 [0.07127652]
 [0.45087418]
 [0.3334085 ]]

In [34]:
# Convert probabilities to binary predictions
y_pred = (y_pred_prob >= 0.5).astype(int)

In [35]:
accuracy = accuracy_score(y_test, y_pred)

print("Model Accuracy:", round(accuracy * 100, 2), "%")

Model Accuracy: 74.03 %

In [36]:
cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[79 20]
 [20 35]]

In [37]:
import pandas as pd

cm_df = pd.DataFrame(
    cm,
    index=["Actual: No Diabetes", "Actual: Diabetes"],
    columns=["Predicted: No Diabetes", "Predicted: Diabetes"]
)

cm_df

                     Predicted: No Diabetes  Predicted: Diabetes
Actual: No Diabetes                      79                   20
Actual: Diabetes                         20                   35

The ANN model performed reasonably well in predicting diabetes. Out of 99 patients who did not have diabetes, the model correctly identified 79 of them, while 20 were incorrectly predicted as having diabetes. Similarly, out of 55 patients who had diabetes, the model correctly identified 35 patients, but 20 diabetic patients were incorrectly classified as non-diabetic.